#!/bin/bash

# Update Homebrew
echo "Updating Homebrew..."
brew update

# Upgrade any installed packages
echo "Upgrading installed packages..."
brew upgrade

# Remove formulae that were installed as dependencies but are no longer actively used
# or required by any other installed software
echo "Removing unused dependencies..."
brew autoremove

# Perform cleanup of cash files and recent downloads older than 17 days
echo "Cleaning up..."
brew cleanup --prune=17

# Remove everything in Homebrew’s prefix that are not needed,
# including symlinks, directories, and the older versions of packages
echo "Cleaning up old versions..."
brew cleanup --prune-prefix

echo "Maintenance tasks complete."
